# This file was automatically generated by weform 0.7.2. Do not edit it
# manually.

locals {
  service    = "ambassadors"
  costcenter = ""
}

variable region {
  default = "eu-west-1"
}

variable aws_profile {
  default = "wetransfer-users-mfa"
}
